#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidGridView.Resource", IsApplication=true)]

namespace AndroidGridView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040010
			public const int black = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int black_overlay = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int customeblue = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int darkblue = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int darkgreen = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int darkorange = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int darkpurple = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int darkred = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int lowDarkfont = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int orange = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int purple = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int red = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int white = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int whiteback = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int whitebackground = 2130968591;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Layth = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int Image = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Text = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int Text1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Text2 = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int gridView1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TicketView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
